name: pull-request-workflow
run-name: Pull request workflow
on: [pull_request]
jobs:
  verify-website-build:
    name: Verify Website Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Changes
        uses: actions/checkout@v4
      # - name: Install Build Dependencies
      #   run: sudo snap install hugo
      # - name: Build Website
      #   run: hugo
      
